# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "npm run build:preview"
publish = "public"

[build.environment]
GO_VERSION = "1.22.2"
HUGO_VERSION = "0.147.0"

# Explicitly enable idiomatic version files for Node.js and
NODE_VERSION = "lts/*"

[context.production]
command = "npm run build:production"

[[redirects]]
  from = "https://shoptima.uz/*"
  to = "https://shoptima.netlify.app/uz/:splat"
  status = 200
  force = true